/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.alumnogui;

import dao.AlumnoDAOSql;
import dao.AlumnoDAOTxt;
import dao.DAO;
import dao.DAOException;
import dao.DAOFactory;
import dao.DAOFactoryException;
import enums.CrudAction;
import exceptions.PersonaException;
import java.awt.Color;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import persona.Alumno;

/**
 *
 * @author g.guzman
 */
public class AlumnoGUI extends javax.swing.JFrame {

    private DAO<Alumno, Integer> dao;
    private AlumnoDAOTxt daoTXT;
    private AlumnoDAOSql daoSQL;
    private final AlumnosTableModel alumnosModel;
    private List<Alumno> alumnos;
    private boolean conectado = false;

    /**
     * Creates new form AlumnoGUI
     */
    public AlumnoGUI() {
        initComponents();
        setLocationRelativeTo(null);
        txtPanel.setVisible(repoComboBox.getSelectedIndex() == 0);
        sqlPanel.setVisible(repoComboBox.getSelectedIndex() == 1);

        alumnosModel = new AlumnosTableModel();
        alumnosTable.setModel(alumnosModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosTable = new javax.swing.JTable();
        crearButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        incluirEliminadosCheck = new javax.swing.JCheckBox();
        txtPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fullpathTextField = new javax.swing.JTextField();
        chooserButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        repoComboBox = new javax.swing.JComboBox<>();
        sqlPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();
        connSQLButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        alumnosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(alumnosTable);

        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        incluirEliminadosCheck.setText("Incluir Eliminados");
        incluirEliminadosCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirEliminadosCheckActionPerformed(evt);
            }
        });

        txtPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Ruta archivo:");

        fullpathTextField.setEditable(false);

        chooserButton.setText("...");
        chooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtPanelLayout = new javax.swing.GroupLayout(txtPanel);
        txtPanel.setLayout(txtPanelLayout);
        txtPanelLayout.setHorizontalGroup(
            txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullpathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtPanelLayout.setVerticalGroup(
            txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fullpathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooserButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel2.setText("Tipo de Repositorio:");

        repoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TXT", "SQL" }));
        repoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repoComboBoxActionPerformed(evt);
            }
        });

        sqlPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("URL:");

        urlTextField.setText("jdbc:mysql://localhost:3306/caba");

        jLabel4.setText("User:");

        userTextField.setText("root");

        jLabel5.setText("Clave:");

        pwdTextField.setText("root");

        connSQLButton.setBackground(new java.awt.Color(0, 204, 0));
        connSQLButton.setText("Conectar");
        connSQLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connSQLButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sqlPanelLayout = new javax.swing.GroupLayout(sqlPanel);
        sqlPanel.setLayout(sqlPanelLayout);
        sqlPanelLayout.setHorizontalGroup(
            sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sqlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sqlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(connSQLButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(sqlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sqlPanelLayout.setVerticalGroup(
            sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sqlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(pwdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(connSQLButton))
                    .addGroup(sqlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(incluirEliminadosCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(crearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(repoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sqlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(repoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sqlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(incluirEliminadosCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(crearButton)
                        .addGap(18, 18, 18)
                        .addComponent(modificarButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(consultarButton)
                        .addGap(63, 63, 63))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repoComboBoxActionPerformed
        /*
        txtPanel.setVisible(repoComboBox.getSelectedIndex()==0);
        sqlPanel.setVisible(repoComboBox.getSelectedIndex()==1);
         */
        if (repoComboBox.getSelectedIndex() == 0) {
            {
                String path = fullpathTextField.getText().trim();
                if (!path.isEmpty()) {
                    try {
                        Map<String, String> config = new HashMap<>();
                        config.put(DAOFactory.TIPO_DAO, "TIPO_DAO_TXT");
                        config.put(DAOFactory.FULLPATH, path);
                        daoTXT = (AlumnoDAOTxt) DAOFactory.getInstance().buildDAO(config);
                    } catch (DAOFactoryException ex) {
                        JOptionPane.showMessageDialog(this, "Error al crear DAO TXT: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            if (daoTXT != null) {
                dao = daoTXT;
                try {
                    actualizarTabla(); // Recarga la tabla desde TXT
                } catch (DAOException ex) {
                    JOptionPane.showMessageDialog(this, "Error al cargar alumnos desde TXT: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                alumnosModel.setAlumnos(List.of());
                alumnosModel.fireTableDataChanged();
            }

            txtPanel.setVisible(true);
            sqlPanel.setVisible(false);
        } else {
            if (daoSQL != null) {
                dao = daoSQL;
                try {
                    actualizarTabla(); // Recarga la tabla desde SQL
                } catch (DAOException ex) {
                    JOptionPane.showMessageDialog(this, "Error al cargar alumnos desde SQL: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                alumnosModel.setAlumnos(List.of()); // Limpia la tabla si no hay DAO inicializado (osea si no hay conexion)
                alumnosModel.fireTableDataChanged();
            }

            txtPanel.setVisible(false);
            sqlPanel.setVisible(true);
        }

    }//GEN-LAST:event_repoComboBoxActionPerformed

    private void chooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter(null, "txt", "json");
        fileChooser.setFileFilter(filter);
        int resp = fileChooser.showOpenDialog(this);
        if (resp != JFileChooser.APPROVE_OPTION) {
            return;
        }

        fullpathTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
        try {
            Map<String, String> config = new HashMap<>();
            config.put(DAOFactory.TIPO_DAO, "TIPO_DAO_TXT");
            config.put(DAOFactory.FULLPATH, fullpathTextField.getText());
            daoTXT = (AlumnoDAOTxt) DAOFactory.getInstance().buildDAO(config);
            dao = daoTXT;

            actualizarTabla();
        } catch (DAOException | DAOFactoryException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_chooserButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Mensaje de confirmación
        //JOptionPane.showConfirmDialog(repoComboBox, evt, title, WIDTH, HEIGHT)
        int selectedRow = alumnosTable.getSelectedRow();

        switch (selectedRow) {
            case -1:
                JOptionPane.showMessageDialog(this, "Seleccioná un alumno para eliminar.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;

            default:
                // Confirmación
                int confirm = JOptionPane.showConfirmDialog(
                        this,
                        "¿Estás seguro que querés eliminar este alumno?",
                        "Confirmar eliminación",
                        JOptionPane.YES_NO_OPTION
                );

                switch (confirm) {
                    case JOptionPane.YES_OPTION:
                    try {
                        Integer dniAlu = alumnos.get(selectedRow).getDni();
                        dao.delete(dniAlu); // Baja lógica
                        actualizarTabla();  // Refrescar tabla
                    } catch (DAOException ex) {
                        Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "Error al eliminar el alumno.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;

                    case JOptionPane.NO_OPTION:
                    default:
                        // No hacer nada si el usuario cancela
                        break;
                }
                break;
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        String fullpath = fullpathTextField.getText().trim();

        // segun repositorio elegido 
        if ((repoComboBox.getSelectedIndex() == 0 && (fullpath.isEmpty() || dao == null)) || (repoComboBox.getSelectedIndex() == 1 && dao == null)) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un repositorio válido antes de crear un alumno.", "Seleccione un repositorio", JOptionPane.WARNING_MESSAGE);
            return;
        }

        AluDialog aluDialog = new AluDialog(this, true, CrudAction.CREATE, null);
        aluDialog.setVisible(true);

        Alumno alu = aluDialog.getAlu();

        if (alu != null) {
            try {
                alu.setEstado('A');
                dao.create(alu);
                actualizarTabla();
                JOptionPane.showMessageDialog(this, "Alumno creado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (NullPointerException | NumberFormatException | DAOException | PersonaException ex) {
                JOptionPane.showMessageDialog(this, "Seleccione el archivo para crear un alumno. '[crearButtonActionPerformed ]', intentalo nuevamente." + ex, "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Creación cancelada", "Cancelado", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_crearButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        int selectedRow = alumnosTable.getSelectedRow();

        if (selectedRow != -1) {
            // traemos el alumno seleccionado desde la lista
            Alumno selectedAlumno = alumnos.get(selectedRow);

            // aca abrimos el AluDialog pasando el CrudAction UPDATE
            AluDialog aluDialog = new AluDialog(this, true, CrudAction.UPDATE, selectedAlumno);
            aluDialog.setVisible(true);

            // aca obtenemos el alumno modificado desde el AluDialog
            Alumno aluModificado = aluDialog.getAlu();

            try {
                if (aluModificado != null) {
                    //al uodate le pasamos el alumno modifido que guardamos en el tipo de dato aluModificado
                    dao.update(aluModificado);
                    //y procedemos a actualizar la tabla
                    actualizarTabla();
                }
            } catch (DAOException ex) {
                Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccioná un alumno para modificar.", "Atención", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_modificarButtonActionPerformed

    private void actualizarTabla() throws DAOException {
        boolean incluirEliminados = incluirEliminadosCheck.isSelected(); // obtenemos si está tildado
        alumnos = dao.findAll(incluirEliminados); // pasamos true o false según el checkbox
        alumnosModel.setAlumnos(alumnos);
        alumnosModel.fireTableDataChanged();
    }


    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        int selectedRow = alumnosTable.getSelectedRow();

        if (selectedRow != -1) {
            Alumno selectedAlu = alumnos.get(selectedRow);
            AluDialog aluDialog = new AluDialog(this, true, CrudAction.READ, selectedAlu);
            aluDialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccioná un alumno para Consultar.", "Atención", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void incluirEliminadosCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirEliminadosCheckActionPerformed
        // TODO add your handling code here:
        try {
            actualizarTabla();
        } catch (DAOException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_incluirEliminadosCheckActionPerformed

    private void connSQLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connSQLButtonActionPerformed
        // TODO add your handling code here:

        try {
            if (!conectado) {//se lee...si conectado es distinto de false, osea, si es TRUE, continuo con el MAP
                Map<String, String> config = new HashMap<>();
                config.put(DAOFactory.TIPO_DAO, "TIPO_DAO_SQL");//aca le asignamos el daoFactory
                config.put(DAOFactory.URL_SQL, urlTextField.getText());
                config.put("USER", userTextField.getText());
                config.put("PASSWORD", pwdTextField.getText());
                daoSQL = (AlumnoDAOSql) DAOFactory.getInstance().buildDAO(config);
                dao = daoSQL;
                actualizarTabla();
                //JOptionPane.showMessageDialog(this, "Conexión SQL establecida correctamente.");//Cuando se establece la conexion...
                connSQLButton.setText("DESCONECTAR");//... mostramos DESCONECTAR en el boton
                connSQLButton.setBackground(Color.RED);// cambiamos el color al mosrtar DESCONECTAR
            } else {//sino, si conectado es FALSE: 
                if (daoSQL != null) {//entonces si daosql esta instancido, siendo distinto de null.
                    daoSQL.close();//cierro la conexion
                    daoSQL = null;//fuerzo a que sea null
                }
                dao = null;//aseguro cerrar la conexion al siguiente DAO: dao = daoSQL = (AlumnoDAOSql) DAOFactory.getInstance().buildDAO(config);
                //JOptionPane.showMessageDialog(this, "Conexión cerrada correctamente.");
                alumnosModel.limpiar();//se creo este metodo para limpiar el listado, que genera un clear sobre la Jtable
                connSQLButton.setText("CONECTAR");//entonces volvemos a mostrar el CONECTAR
                connSQLButton.setBackground(Color.GREEN);
            }
            conectado = !conectado;
        } catch (DAOException | DAOFactoryException ex) {
            JOptionPane.showMessageDialog(this, "Error:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_connSQLButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            if (daoSQL != null) {
                daoSQL.close();
                JOptionPane.showMessageDialog(this, "Conexión cerrada.");
            }
            

        } catch (DAOException ex) {
            Logger.getLogger(AlumnoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alumnosTable;
    private javax.swing.JButton chooserButton;
    private javax.swing.JButton connSQLButton;
    private javax.swing.JButton consultarButton;
    private javax.swing.JButton crearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField fullpathTextField;
    private javax.swing.JCheckBox incluirEliminadosCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JComboBox<String> repoComboBox;
    private javax.swing.JPanel sqlPanel;
    private javax.swing.JPanel txtPanel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
